services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  minio-mc:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      set -e;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb -p myminio/local-data || true;
      echo 'Syncing local ./data to bucket...';
      mc mirror --overwrite --watch /data myminio/local-data;
      "
    volumes:
      - ./data:/data:ro

volumes:
  minio_data:
